DROP DATABASE IF EXISTS Sample_HR;
CREATE DATABASE Sample_HR;
USE Sample_HR;


DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES (
	EMP_ID		TINYINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    F_NAME		VARCHAR(10) NOT NULL,
    L_NAME		VARCHAR(10) NOT NULL,
    SSN			TINYINT UNSIGNED NOT NULL,
    B_DATE		DATE NOT NULL,
    SEX			ENUM('M', 'F') NOT NULL,
    ADDRESS		NVARCHAR(50)  NOT NULL,
    JOB_ID		TINYINT UNSIGNED NOT NULL UNIQUE KEY,
    SALARY		TINYINT UNSIGNED NOT NULL,
    MANAGER_ID	INT UNSIGNED NOT NULL,
    DEP_ID		TINYINT UNSIGNED NOT NULL UNIQUE KEY
);

DROP TABLE IF EXISTS JOB_HISTORY;
CREATE TABLE JOB_HISTORY (
	EMPL_ID		TINYINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    START_DATE	DATETIME DEFAULT NOW(),
    JOBS_ID		TINYINT UNSIGNED NOT NULL,
    DEPT_ID		TINYINT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS JOBS;
CREATE TABLE JOB_HISTORY (
	JOB_IDENT	TINYINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    JOB_TITLE	VARCHAR(25) NOT NULL,
    MIN_SALARY	TINYINT UNSIGNED NOT NULL,
    MAX_SALARY	TINYINT	UNSIGNED NOT NULL
);
DROP TABLE IF EXISTS DEPARTMENTS;
CREATE TABLE DEPARTMENTS (
	DEPT_ID_DEP	TINYINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    DEP_NAME	VARCHAR(25) NOT NULL,
    MANAGER_ID	TINYINT UNSIGNED NOT NULL,
    LOC_ID		TINYINT	UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS LOCATIONS;
CREATE TABLE JOB_HISTORY (
	LOCT_ID	TINYINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    DEP_ID_LOC	VARCHAR(25) NOT NULL,
    MIN_SALARY	TINYINT UNSIGNED NOT NULL,
    MAX_SALARY	TINYINT	UNSIGNED NOT NULL
);